ARG PYTORCH="1.6.0"
ARG CUDA="10.1"
ARG CUDNN="7"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

# Add keys and update apt-get
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

RUN apt-get update && apt-get install -y git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 ffmpeg

# Environment variables for PyTorch
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
ENV FORCE_CUDA="1"

# Install mmcv-full
RUN pip install --upgrade pip
RUN pip install mmcv-full==latest+torch1.6.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html

# Clone repositories and set up workspace
RUN conda clean --all
RUN git clone https://github.com/grayson1999/AccidentFaultAI.git /AccidentFaultAI
WORKDIR /AccidentFaultAI
RUN git clone https://github.com/grayson1999/TSNAccidentAnalysis.git /AccidentFaultAI/mmaction2
WORKDIR /AccidentFaultAI/mmaction2
RUN mkdir -p /AccidentFaultAI/datasets/data

# Install Python dependencies
RUN pip install cython --no-cache-dir
RUN pip install --no-cache-dir -e .

# Return to the main directory
WORKDIR /AccidentFaultAI

# Install YOLO and other required packages
RUN pip install numpy --upgrade
RUN pip install ultralytics
RUN pip install opencv-contrib-python==4.5.5.62
